apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yq8648i9a-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yq8648i9a-dotnet-basic-gitops